### PR TITLE
Inflictor fix

### PR DESCRIPTION
**Pull request by NickCloudAT**
Improvised fix for GetInflictor.

### CODE REVIEW

**Comment by Alf21** [comment]
Couldn't you just set the sidekick deagle as inflictor and check this instead of checking whether the active (current) weapon is the sidekick deagle?

**Comment by NickCloudAT** [comment]
Well if you tell me where I should do so.. But in my mind thinkin about that, it would still not fix that?
I mean, how would I AT FIRST check that it's the sidekick deagle that shot, and then set it as inflictor? I mean I can't set it as inflicor when it was damage from like a grenade or so.

**Comment by Alf21** [comment]
AFAIK you don‘t need to set the inflictor manually. This should be done automatically if you are doing damage with this weapon.

**Comment by NickCloudAT** [comment]
Yeah but dmginfo:GetInflictor() does not return the sidekick deagle, only the Player. 
It only returns entitys like grenades or projectiles for me.. and for what ever reason also my crowbar.

**Comment by Alf21** [comment]
Is this still a thing?

**Comment by lebroomer** [comment]
I think, I have a solution for this problem: We can use ShootBullet with a callback function for a save feedback. I can test this and draft a new PR if you want to :)

**Comment by Alf21** [comment]
Hmm if it‘s still a bug and you have a nice solution, it would be really helpful :)

**Pull request closed without merging**
